# Generated by Django 5.2 on 2026-01-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Dummy field - not used for login', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
