# Generated by Django 5.1.6 on 2026-01-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category_alter_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'In-App Chat')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='date_lost',
            field=models.DateField(blank=True, help_text='When did you lose this item?', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reward_offered',
            field=models.CharField(blank=True, help_text="Optional: e.g. '$20 reward' or 'Coffee on me!'", max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_question',
            field=models.TextField(blank=True, help_text='Ask a question only the owner would know'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Keys', 'Keys'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('ID/Cards', 'ID/Cards'), ('Bags', 'Bags'), ('Other', 'Other')], help_text='Select a category', max_length=50, null=True),
        ),
    ]
