# Generated by Django 5.1.6 on 2026-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_contact_preference_item_date_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
