# Generated by Django 5.2 on 2026-01-25 19:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Type the location (e.g. Main Library, Science Cafe...)', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload photo of the item', max_length=255, null=True, verbose_name='image'),
        ),
    ]
