# Generated by Django 6.0.1 on 2026-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_location_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Optional: your email or WhatsApp number (e.g. whatsapp:+2348012345678)', max_length=200),
        ),
    ]
