# Generated by Django 6.0.1 on 2026-01-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_contact_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact_preference',
        ),
        migrations.AddField(
            model_name='item',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who claimed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email address', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your phone/WhatsApp number (e.g. +2348012345678)', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Share your experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.item')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'reviewer')},
            },
        ),
    ]
