# Generated by Django 5.2 on 2026-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='item',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Optional: your email or WhatsApp number (e.g. whatsapp:+2348012345678)', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'In-App Chat')], default='chat', max_length=20),
        ),
    ]
