# Generated by Django 5.1.6 on 2026-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Keys', 'Keys'), ('Books', 'Books'), ('Clothing', 'Clothing')], help_text='Select a category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Type the location (e.g. Main Library, Science Cafe, Student Union...)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
